In [1]:
# importamos todas las librer√≠as que necesitamos

import pandas as pd
pd.options.display.max_columns = None
import re
import regex as re
import numpy as np
import datetime

### Pair Programming Pandas VII

En el ejercicio de ayer estuvimos viendo el groupby y pudimos observar que los datos estaban un poco sucios... üò≠. En los ejercicios de hoy pondremos en pr√°ctica los apply y nos crearemos algunas funciones que nos van a permitir limpiar un poco los datos, para que podamos extraer conclusiones de una forma m√°s sencilla.

In [2]:
df = pd.read_csv("datos/05-attacks_union.csv", index_col = 0)
df.head(5)

,case_number,year,type,country,area,location,activity,name,sex,age,time,species,href,siglo,investigator_or_source,pdf,href_formula,case_number.1,case_number.2,original_order,fatal_(y/n),injury,date
0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018
1,2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,Y,FATAL,03-Jun-2018
2,2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,Lower left leg bitten,26-May-2018
3,2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,Minor bite to hand by captive shark. PROVOKED ...,24-May-2018
4,2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,Injured by teeth of a dead porbeagle shark he ...,13-May-2018

### 1. Cread una columna nueva y una funci√≥n que nos d√© el mes en el que ocurri√≥ el ataque. 

Tened en cuenta que no todas las filas tienen la misma estructura 
y que puede que no haya la informaci√≥n de mes. En ese caso devolved un nulo (NaN).
üí° Pista üí°Pod√©is usar regex.

In [3]:
date_unique = df["date"].unique()
date_unique

array(['25-Jun-2018', '03-Jun-2018', '26-May-2018', ..., '1900-1905',
       '1883-1889', '1845-1853'], dtype=object)

In [4]:
def fecha(x):
    try:
        return re.findall('([A-Z]{1}[a-z]{2})\-',x)[0]
    except:
        return np.nan

In [5]:
df['mes'] = df['date'].apply(fecha)

In [6]:
df.head(2)

,case_number,year,type,country,area,location,activity,name,sex,age,time,species,href,siglo,investigator_or_source,pdf,href_formula,case_number.1,case_number.2,original_order,fatal_(y/n),injury,date,mes
0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,Jun
1,2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,Y,FATAL,03-Jun-2018,Jun

### 2. Vamos con la columna fatal_(y/n). 
Lo primero que ten√©is que hacer es evaluar los valores √∫nicos que hay. Esperar√≠amos tener solo dos valores: y y n, pero tristemente no ser√° as√≠ üò≠. Cread una columna nueva y una funci√≥n que devuelva √∫nicamente y o n y que devuelva un nulo (NaN) si no se encuentra el valor.

In [7]:
df["fatal_(y/n)"].unique()

array(['N', 'Y', nan, 'M', '2017', ' N', 'UNKNOWN'], dtype=object)

In [8]:
def yn(x):
    if x == "N":
        return "N"
    elif x == "Y":
        return "Y"
    elif x == " N":
        return "N"
    elif x == "N ":
        return "N"
    elif x == "y":
        return "Y"
    else:
        return np.nan

In [9]:
df["fatal"] = df["fatal_(y/n)"].apply(yn)
df.head(2)

,case_number,year,type,country,area,location,activity,name,sex,age,time,species,href,siglo,investigator_or_source,pdf,href_formula,case_number.1,case_number.2,original_order,fatal_(y/n),injury,date,mes,fatal
0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,Jun,N
1,2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,Y,FATAL,03-Jun-2018,Jun,Y

In [10]:
df["fatal"].unique()

array(['N', 'Y', nan], dtype=object)

### 3. Seguid la misma l√≥gica que en el ejercicio anterior pero con la columna sex. 
Pero en este caso vamos a incluir un retito m√°s: En este caso querremos tener dos valores √∫nicos F y M. De nuevo en la columna hay otros car√°cteres raros como 'M ', 'lli', 'N', '.'. En esos casos, queremos que se reemplacen por M o F de forma aleatoria (tendr√©is que usar la librer√≠a random). En caso de que sea nulo, que la funci√≥n devuelva nulo (np.nan).

In [11]:
df["sex"].unique()

array(['F', 'M', 'lli', nan], dtype=object)

In [12]:
def reemplazar_mf(x):
    if x == "F":
        return "F"
    elif x == "M":
        return "M"
    else:
        return np.nan

In [13]:
df["sex_fm"] = df["sex"].apply(reemplazar_mf)
df.head(5)

,case_number,year,type,country,area,location,activity,name,sex,age,time,species,href,siglo,investigator_or_source,pdf,href_formula,case_number.1,case_number.2,original_order,fatal_(y/n),injury,date,mes,fatal,sex_fm
0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,Jun,N,F
1,2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,Y,FATAL,03-Jun-2018,Jun,Y,M
2,2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,Lower left leg bitten,26-May-2018,May,N,M
3,2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,Minor bite to hand by captive shark. PROVOKED ...,24-May-2018,May,N,M
4,2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,N,Injured by teeth of a dead porbeagle shark he ...,13-May-2018,May,N,M

In [14]:
df["sex_fm"].unique()

array(['F', 'M', nan], dtype=object)

### 4. Una vez que hay√°is terminado eliminad las columnas originales conservando las nuevas.

In [15]:
df.drop(["fatal_(y/n)", "sex"], axis = 1, inplace = True)

In [16]:
df.head(5)

,case_number,year,type,country,area,location,activity,name,age,time,species,href,siglo,investigator_or_source,pdf,href_formula,case_number.1,case_number.2,original_order,injury,date,mes,fatal,sex_fm
0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,"No injury to occupant, outrigger canoe and pad...",25-Jun-2018,Jun,N,F
1,2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,FATAL,03-Jun-2018,Jun,Y,M
2,2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,Lower left leg bitten,26-May-2018,May,N,M
3,2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,Minor bite to hand by captive shark. PROVOKED ...,24-May-2018,May,N,M
4,2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI,NaN,NaN,NaN,NaN,NaN,NaN,Injured by teeth of a dead porbeagle shark he ...,13-May-2018,May,N,M

### 5. Guardad el dataframe en un csv que usaremos m√°s adelante.

In [17]:
df.to_csv("datos/07-attack.csv")